import type { Metadata } from "next";

export const metadata: Metadata = {
  title: `product `,
  description: "Generated by product",
};


export async function generateStaticParams() {
  const products: string[] = ["1", "2", "3", "4", "5"];

  return products.map((id) => ({
    id: id,
  }));
} 





async function getData(id: number) {
  const res = await fetch(
    `https://shoaib-third-task.vercel.app/api/products/${id}`,
    {
      cache: "no-cache",
    }
  );
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function GiveProduct(props: { params: { id: number } }) {
  const product = await getData(props.params.id);
  console.log(product);

  return (
    <div className="flex justify-center mt-28">
      <div className="-mt-2 p-2 lg:mt-0 lg:w-full lg:max-w-md lg:flex-shrink-0">
        <div className="rounded-2xl bg-gray-700  py-10 text-center ring-1 ring-inset ring-gray-900/5 lg:flex lg:flex-col lg:justify-center lg:py-16">
          <div className="mx-auto max-w-xs px-8">
            <p className=" font-semibold text-white text-3xl">
              {product.name}
            </p>
            <p className="mt-6 flex items-baseline justify-center gap-x-2">
              <span className="text-5xl font-bold tracking-tight text-white">
                ${product.price}
              </span>
              <span className="text-sm font-semibold leading-6 tracking-wide text-white">
                USD
              </span>
            </p>

            <p className="mt-6 text-s leading-5 text-white">
              {product.description}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
